name: web_clipboard
description: Playing with the Web Clipboard API
author: Jaween Ediriweera
version: 1.0.0
dependencies:
  js: ^0.6.2
dev_dependencies:
  build_web_compilers: any
  build_runner: any