name: google_play_aus_gst
description: Calculate GST that needs to be remitted to the ATO on Australian Google Play sales
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'
  
dependencies:
  path: ^1.7.0
  csv: ^5.0.0
  intl: ^0.17.0

